package io.github.dst;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dstefanski' at '2/4/17 11:52 AM' with Gradle 2.13
 *
 * @author dstefanski, @date 2/4/17 11:52 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
