package io.github.dst;

import io.github.dst.Library;
import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'dstefanski' at '2/4/17 11:52 AM' with Gradle 2.13
 *
 * @author dstefanski, @date 2/4/17 11:52 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
